server:
  port: 8080

spring:
  application:
    name: payment-service-app
  datasource:
    url: jdbc:postgresql://localhost:5432/payment-db
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
        hibernate:
          format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/iprody-lms


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers

logging:
  level:
    com.iprody.payment: DEBUG
    org.springframework.web: INFO
    org.springframework.data: INFO
    org.springframework.security: INFO
