server:
  port: 8080

spring:
  application:
    name: payment-service-app
  datasource:
    url: jdbc:postgresql://localhost:5432/payment-db
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
        hibernate:
          format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/iprody-lms

  kafka:
    bootstrap-servers: localhost:9093

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: xpayment-adapter-result-consumers
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "com.iprody.payment.service.app.async"
        spring.json.value.default.type: "com.iprody.payment.service.app.async.XPaymentAdapterResponseMessage"

    listener:
      ack-mode: manual
      concurrency: 1

app:
  kafka:
    topics:
      x-payment-adapter:
        request: x-payment-adapter.requests
        response: x-payment-adapter.responses

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers

logging:
  level:
    com.iprody.payment: info
    org.springframework.web: error
    org.springframework.data: error
    org.springframework.security: error
    root: info
