version: '3.8'

services:
#  payment-service-app:
#    image: payment-service-app:latest
#    ports:
#      - "8080:8080"

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin # имя пользователя
      POSTGRES_PASSWORD: secret # пароль
      POSTGRES_DB: payment-db # имя БД по умолчанию
    ports:
    - "5432:5432" # проброс порта PostgreSQL
    volumes:
    - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
    pgdata: